#ifndef ASCE_H
#define ASCE_H

typedef enum{
    ASSO_AARQ                   = TAG_APPLICATION + TAG_CONSTRUCTED + 0U,   ///< Application number 0
    ASSO_AARE                   = TAG_APPLICATION + TAG_CONSTRUCTED + 1U,   ///< Application number 1
    ASSO_RLRQ                   = TAG_APPLICATION + TAG_CONSTRUCTED + 2U,   ///< Application number 2
    ASSO_RLRE                   = TAG_APPLICATION + TAG_CONSTRUCTED + 3U,   ///< Application number 3
    ASSO_PROTO_VER              = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE,
    ASSO_APP_CONTEXT_NAME       = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  1U,

    // AARQ tags
    AARQ_CALLED_AP_TITLE        = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  2U,
    AARQ_CALLED_AE_QUALIFIER    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  3U,
    AARQ_CALLED_AP_INVOC_ID     = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  4U,
    AARQ_CALLED_AE_INVOC_ID     = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  5U,
    AARQ_CALLING_AP_TITLE       = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  6U,
    AARQ_CALLING_AE_QUALIFIER   = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  7U,
    AARQ_CALLING_AP_INVOC_ID    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  8U,
    AARQ_CALLING_AE_INVOC_ID    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  9U,
    AARQ_SENDER_ACSE_REQU       = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   + 10U,
    AARQ_REQ_MECHANISM_NAME     = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   + 11U,
    AARQ_CALLING_AUTH_VALUE     = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 12U,
    AARQ_IMPLEMENTATION_INFO    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 29U,
    AARQ_USER_INFORMATION       = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 30U,

    // AARE tags
    CSM_ASSO_RESP_AUTH_VALUE        = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  10U,
    CSM_ASSO_RESP_MECHANISM_NAME    = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   +  9U,
    CSM_ASSO_RESPONDER_ACSE_REQ     = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   +  8U,
    CSM_ASSO_RESP_AP_TITLE          = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  4U,
    CSM_ASSO_RESULT_FIELD           = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  2U,
    CSM_ASSO_RESULT_SRC_DIAG        = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  3U,
    CSM_ASSO_RESULT_SERVICE_USER    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  1U,
} csm_asso_tag;

enum aarq_tags{
    PROTOCOL_VERSION       = 0x00,
    APP_CONTEXT_NAME       = 0x01,
    CALLED_AP_TITLE        = 0x02,
    CALLED_AE_QUALIFIER    = 0x03,
    CALLED_AP_INVOC_ID     = 0x04,
    CALLED_AE_INVOC_ID     = 0x05,
    CALLING_AP_TITLE       = 0x06,
    CALLING_AE_QUALIFIER   = 0x07,
    CALLING_AP_INVOC_ID    = 0x08,
    CALLING_AE_INVOC_ID    = 0x09,
    SENDER_ACSE_REQU       = 0x10,
    REQ_MECHANISM_NAME     = 0x11,
    CALLING_AUTH_VALUE     = 0x12,
    IMPLEMENTATION_INFO    = 0x29,
    USER_INFORMATION       = 0x30,
};

#endif //ASCE_H