#ifndef APDU_TYPES_H
#define APDU_TYPES_H

#include "asn1.h"

enum asce_tag_mask{
    ASCE_AARQ_MASK         = 0x00U,
    ASCE_AARE_MASK         = 0x01U,
    ASCE_RLRQ_MASK         = 0x02U,
    ASCE_RLRE_MASK         = 0x03U,
};

enum asce_tag{
    ASCE_AARQ        = TAG_APPLICATION + TAG_CONSTRUCTED + ASCE_AARQ_MASK,
    ASCE_AARE        = TAG_APPLICATION + TAG_CONSTRUCTED + ASCE_AARE_MASK,
    ASCE_RLRQ		 = TAG_APPLICATION + TAG_CONSTRUCTED + ASCE_RLRQ_MASK,
    ASCE_RLRE		 = TAG_APPLICATION + TAG_CONSTRUCTED + ASCE_RLRE_MASK,
};

// enum xdlms_tag{
//     AXDR_BAD_TAG            = 0U,
//     AXDR_INITIATE_REQUEST   = 1U,
//     AXDR_INITIATE_RESPONSE  = 8U,
//     AXDR_GET_REQUEST        = 192U,
//     AXDR_SET_REQUEST        = 193U,
//     AXDR_ACTION_REQUEST     = 195U,
//     AXDR_GET_RESPONSE       = 196U,
//     AXDR_SET_RESPONSE       = 197U,
//     AXDR_ACTION_RESPONSE    = 199U,
//     AXDR_EXCEPTION_RESPONSE = 216U
// };

enum aarq_tags{
    AARQ_CALLED_AP_TITLE        = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  2U,
    AARQ_CALLED_AE_QUALIFIER    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  3U,
    AARQ_CALLED_AP_INVOC_ID     = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  4U,
    AARQ_CALLED_AE_INVOC_ID     = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  5U,
    AARQ_CALLING_AP_TITLE       = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  6U,
    AARQ_CALLING_AE_QUALIFIER   = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  7U,
    AARQ_CALLING_AP_INVOC_ID    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  8U,
    AARQ_CALLING_AE_INVOC_ID    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  9U,
    AARQ_SENDER_ACSE_REQU       = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   + 10U,
    AARQ_REQ_MECHANISM_NAME     = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   + 11U,
    AARQ_CALLING_AUTH_VALUE     = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 12U,
    AARQ_IMPLEMENTATION_INFO    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 29U,
    AARQ_USER_INFORMATION       = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 30U,
};

enum aare_tags{
    AARE_RESP_AUTH_VALUE        = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  10U,
    AARE_RESP_MECHANISM_NAME    = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   +  9U,
    AARE_RESPONDER_ACSE_REQ     = TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE   +  8U,
    AARE_RESP_AP_TITLE          = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  4U,
    AARE_RESULT_FIELD           = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  2U,
    AARE_RESULT_SRC_DIAG        = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  3U,
    AARE_RESULT_SERVICE_USER    = TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED +  1U,
};

#endif // APDU_TYPES_H

// A1  09  06  07  60  85  74  05  08  01  01  BE  10  04  0E  01  00  00  00  06  5F  1F  04  00  00  1E  1D  FF  FF